apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twistreview.fullname" . }}
  labels:
    {{- include "twistreview.labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: health,info
    spring:
      data:
        mongodb:
          host: ${MONGO_HOST}
          port: ${MONGO_PORT}
          username: ${MONGO_USERNAME}
          password: ${MONGO_PASSWORD}
          database: twistreview
