# Prod overrides for twistreview
replicaCount: 2

image:
  repository: crostonj/techtwist-review
  tag: "raspberry-pi"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: twistreview.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: twistreview-tls
      hosts:
        - twistreview.example.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

podAnnotations: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: "/reviews"
  - name: MONGO_HOST
    value: "mongo"
  - name: MONGO_PORT
    value: "27017"
  - name: MONGO_USERNAME
    valueFrom:
      secretKeyRef:
        name: twistreview-secrets
        key: mongo-username
  - name: MONGO_PASSWORD
    valueFrom:
      secretKeyRef:
        name: twistreview-secrets
        key: mongo-password

secrets:
  enabled: false

serviceAccount:
  create: true
