# Dev overrides for twistreview
replicaCount: 1

image:
  repository: crostonj/techtwist-review
  tag: "raspberry-pi"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: twistreview.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

podAnnotations: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "default"
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: "/reviews"
  - name: MONGO_HOST
    value: "mongo"
  - name: MONGO_PORT
    value: "27017"
  - name: MONGO_USERNAME
    valueFrom:
      secretKeyRef:
        name: twistreview-secrets
        key: mongo-username
  - name: MONGO_PASSWORD
    valueFrom:
      secretKeyRef:
        name: twistreview-secrets
        key: mongo-password

secrets:
  enabled: true
  mongoUsername: ""
  mongoPassword: ""

serviceAccount:
  create: true
