server:
  port: 8080
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:reviews}
      username: ${MONGO_USERNAME:}
      password: ${MONGO_PASSWORD:}
      authentication-database: ${MONGO_AUTH_DB:admin}
