name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image for Raspberry Pi (ARM)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: crostonj/techtwist-review:raspberry-pi
        platforms: linux/arm64

    - name: Build and push image for Intel-based computers (AMD)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: crostonj/techtwist-review:intel
        platforms: linux/amd64

    - name: Log out from Docker Hub
      run: docker logout
